import { initCinema } from './cinema.js';
const $=id=>document.getElementById(id);
const ids=['title','author','width','height','count','paper','caliper','gsm','binding','finish','board','endpapers','bleed','safe','gutter','sourceSize'];
const CLOUD_API=(window.BOOK_CLOUD_API||((location.protocol==='http:'||location.protocol==='https:')?location.origin:'https://book.tohuvavohu2000.workers.dev')).replace(/\/$/,'');
const TOKEN_KEY='book-studio-cloud-token';
const params=new URLSearchParams(location.search);
const headlessRender=params.has('__cloudRenderJob');
let renderToken=params.get('__renderToken')||'';
let mode='demo',page=0,view='shelf',dimensions=null,coverUrl=null,renderId=0,turning=false,busy=false,fileName='',resizeTimer;
let cinema=null,contentRevision=0,cloudCalc=null,calcTimer=null,calcSeq=0;
const cloudFiles={manuscript:null,front:null,wrap:null};
const previewCache=new Map();
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const LOCAL_DB='book-studio-local-v1',LOCAL_DB_VERSION=1,LOCAL_PROJECT_KEY='current';
let localDbPromise=null,localSaveTimer=null,restoringLocal=false;
function openLocalDb(){if(headlessRender||!('indexedDB'in window))return Promise.resolve(null);if(localDbPromise)return localDbPromise;localDbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(LOCAL_DB,LOCAL_DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('files'))db.createObjectStore('files',{keyPath:'kind'});if(!db.objectStoreNames.contains('state'))db.createObjectStore('state',{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return localDbPromise}
async function idbGet(store,key){const db=await openLocalDb();if(!db)return null;return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly'),req=tx.objectStore(store).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
async function idbPut(store,value){const db=await openLocalDb();if(!db)return false;return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function idbDelete(store,key){const db=await openLocalDb();if(!db)return false;return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function requestPersistentLocalStorage(){if(headlessRender||!navigator.storage?.persist)return false;try{return await navigator.storage.persist()}catch{return false}}
async function storeLocalUpload(kind,file,meta){if(headlessRender||!file)return;try{await requestPersistentLocalStorage();await idbPut('files',{kind,file,meta,name:file.name,type:file.type,size:file.size,lastModified:file.lastModified||0,savedAt:Date.now()});scheduleLocalSave()}catch(e){console.warn('Local file save failed',e);toast('הקובץ נשלח לענן, אבל הדפדפן לא הצליח לשמור עותק מקומי. ייתכן שאין מספיק מקום.')}}
async function removeLocalUpload(kind){if(headlessRender)return;try{await idbDelete('files',kind);scheduleLocalSave()}catch(e){console.warn('Local file delete failed',e)}}
function captureLocalState(){return {key:LOCAL_PROJECT_KEY,version:1,savedAt:Date.now(),settings:settings(),source:{manuscript:cloudFiles.manuscript,front:cloudFiles.front,wrap:cloudFiles.wrap},mode,dimensions,fileName,page,view,ui:{rotation:$('rotation')?.value,tilt:$('tilt')?.value,zoom:$('zoom')?.value,guides:$('guides')?.checked,sourceSize:$('sourceSize')?.value},cinema:cinema?.getState?.()||null}}
async function saveLocalProject(){if(headlessRender||restoringLocal)return;try{await idbPut('state',captureLocalState());cloudStatus('ענן + נשמר מקומית','ok')}catch(e){console.warn('Local project save failed',e)}}
function scheduleLocalSave(){if(headlessRender||restoringLocal)return;clearTimeout(localSaveTimer);localSaveTimer=setTimeout(()=>saveLocalProject(),250)}
async function restoreLocalProject(){if(headlessRender)return false;let state;try{state=await idbGet('state',LOCAL_PROJECT_KEY)}catch(e){console.warn('Local restore unavailable',e);return false}if(!state)return false;restoringLocal=true;try{for(const [id,value] of Object.entries(state.settings||{}))if($(id)&&value!==undefined&&value!==null)$(id).value=value;Object.assign(cloudFiles,state.source||{});mode=state.mode||mode;dimensions=state.dimensions||null;fileName=state.fileName||cloudFiles.manuscript?.name||'';page=Number.isFinite(state.page)?state.page:0;if(state.ui?.rotation!=null&&$('rotation'))$('rotation').value=state.ui.rotation;if(state.ui?.tilt!=null&&$('tilt'))$('tilt').value=state.ui.tilt;if(state.ui?.zoom!=null&&$('zoom')){$('zoom').value=state.ui.zoom;$('zoomValue').textContent=state.ui.zoom+'%'}if(state.ui?.guides!=null&&$('guides'))$('guides').checked=Boolean(state.ui.guides);if(state.ui?.sourceSize&&$('sourceSize'))$('sourceSize').value=state.ui.sourceSize;cinema?.restoreState?.(state.cinema||{});if(cloudFiles.manuscript){$('count').max=Math.max(10000,cloudFiles.manuscript.pageCount||1);$('count').value=cloudFiles.manuscript.pageCount||$('count').value;$('count').disabled=true;$('sourceTag').textContent=(fileName||cloudFiles.manuscript.name||'כתב יד')+' · '+count()+' עמודים';$('sourceBadge').textContent=(cloudFiles.manuscript.mode||mode)==='pdf'?'PDF · נשמר מקומית':'Word · נשמר מקומית'}contentRevision++;cloudCalc=null;await requestCalcNow().catch(()=>{});if(cloudFiles.front){try{const img=await imageFromMeta(cloudFiles.front,1,2048);coverUrl=img.src;const art=document.querySelector('.cover-art'),preview=$('frontCoverPreview');art.style.backgroundImage=`url("${coverUrl}")`;art.style.backgroundSize='contain';art.style.backgroundRepeat='no-repeat';document.querySelector('.cover-type').hidden=true;if(preview){preview.style.backgroundImage=`url("${coverUrl}")`;preview.classList.add('has-cover')}cinema?.setFront(img)}catch(e){console.warn('Could not restore front preview',e)}}if(cloudFiles.wrap){try{const img=await imageFromMeta(cloudFiles.wrap,1,2600);cinema?.setWrapFromCloud?.(img,cloudFiles.wrap.name,state.cinema?.wrap||{})}catch(e){console.warn('Could not restore wrap preview',e)}}setView(state.view||'shelf');toast('הפרויקט שוחזר מהשמירה המקומית בדפדפן');return true}finally{restoringLocal=false;scheduleLocalSave()}}

function n(id){const el=$(id),value=Number(el.value);const min=el.min===''?-Infinity:Number(el.min),max=el.max===''?Infinity:Number(el.max);return Math.max(min,Math.min(max,Number.isFinite(value)?value:min));}
function count(){return Math.max(1,Math.floor(n('count')))}
function maxSpread(){return Math.floor(count()/2)}
function toast(message){const t=$('toast'),dialogs=[...document.querySelectorAll('dialog[open]')],host=dialogs.at(-1)||document.body;if(t.parentElement!==host)host.append(t);t.textContent=message;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>{t.style.display='none';if(!document.querySelector('dialog[open]')&&t.parentElement!==document.body)document.body.append(t)},6500)}
function metric(id,value,unit=''){const el=$(id);el.replaceChildren(document.createTextNode(String(value)));if(unit){const em=document.createElement('em');em.textContent=' '+unit;el.append(em)}}
function settings(){return Object.fromEntries(ids.map(id=>[id,$(id).value]))}
function cloudStatus(text,state='working'){const el=$('cloudStatus');if(el){el.textContent=text;el.dataset.state=state}}
function getSavedToken(){return renderToken||sessionStorage.getItem(TOKEN_KEY)||''}
function askToken(){if(headlessRender)return renderToken;let token=sessionStorage.getItem(TOKEN_KEY)||'';if(!token){token=prompt('הזן את קוד הגישה לשרת הענן')||'';if(token)sessionStorage.setItem(TOKEN_KEY,token)}return token}
async function cloudFetch(path,options={},needsAuth=true,retry=true){
 const headers=new Headers(options.headers||{});let token=getSavedToken();if(needsAuth&&!token&&!headlessRender)token=askToken();if(needsAuth&&token)headers.set('Authorization','Bearer '+token);
 let res=await fetch(CLOUD_API+path,{...options,headers});
 if(res.status===401&&needsAuth&&retry&&!headlessRender){sessionStorage.removeItem(TOKEN_KEY);token=askToken();if(token){headers.set('Authorization','Bearer '+token);res=await fetch(CLOUD_API+path,{...options,headers})}}
 if(!res.ok){let msg='שגיאת שרת '+res.status;try{const data=await res.json();msg=data.error||data.message||msg}catch{try{msg=(await res.text())||msg}catch{}}throw Error(msg)}return res;
}
function calcPayload(){return {settings:settings(),mode,dimensions,fileName,source:cloudFiles.manuscript?{id:cloudFiles.manuscript.id,pageCount:cloudFiles.manuscript.pageCount,mode:cloudFiles.manuscript.mode,dimensions:cloudFiles.manuscript.dimensions}:null}}
function applyCalc(calc){cloudCalc=calc;metric('thickness',Number(calc.thicknessMm).toFixed(1),'מ״מ');metric('sheets',calc.sheets);metric('weight',calc.weightGrams,'גרם');metric('wrap',Number(calc.wrapWidthMm).toFixed(1)+' × '+Number(calc.wrapHeightMm).toFixed(1),'מ״מ');$('status').textContent=calc.validation?.message||'החישוב הוחזר מהשרת';$('checkSummary').textContent=calc.validation?.summary||'חישוב ענן';$('statusIcon').className=calc.validation?.warning?'warning':'good';const h=Math.min(410,$('stage').clientHeight-110,($('stage').clientWidth-110)*n('height')/n('width'));$('stage').style.setProperty('--depth',Math.max(3,Number(calc.thicknessMm||1)*h/n('height'))+'px');cloudStatus('מחובר לענן','ok');cinema?.update()}
async function requestCalcNow(){const seq=++calcSeq;cloudStatus('מחשב בענן…','working');try{const res=await cloudFetch('/api/calc',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(calcPayload())},false);const data=await res.json();if(seq===calcSeq)applyCalc(data.calc);return data.calc}catch(e){if(seq===calcSeq){cloudStatus('שגיאת ענן','error');$('status').textContent='לא ניתן לקבל חישוב מהשרת: '+e.message;$('checkSummary').textContent='השרת אינו זמין';$('statusIcon').className='warning'}throw e}}
function requestCalc(){clearTimeout(calcTimer);calcTimer=setTimeout(()=>requestCalcNow().catch(()=>{}),180)}
function update(){
 $('sizeBadge').textContent=n('width')+' × '+n('height')+' מ״מ';document.querySelectorAll('.book-title').forEach(el=>el.textContent=$('title').value||'הספר שלי');document.querySelectorAll('.book-author').forEach(el=>el.textContent=$('author').value);
 const colors={cream:'#f3eedf',white:'#fff',thin:'#f6f5ed',coated:'#fbfcfd',custom:'#f2eee4'};$('stage').style.setProperty('--paper',colors[$('paper').value]);$('book').classList.toggle('gloss',$('finish').value==='gloss');$('sceneMeta').textContent=($('binding').value==='hard'?'כריכה קשה':'כריכה רכה')+' · '+($('finish').value==='gloss'?'למינציה מבריקה':'למינציה מט');
 const h=Math.min(410,$('stage').clientHeight-110,($('stage').clientWidth-110)*n('height')/n('width'));$('stage').style.setProperty('--book-height',h+'px');$('stage').style.setProperty('--book-width',h*n('width')/n('height')+'px');if(cloudCalc)$('stage').style.setProperty('--depth',Math.max(3,Number(cloudCalc.thicknessMm||1)*h/n('height'))+'px');
 $('pageSlider').max=maxSpread();$('jump').max=count();page=Math.min(page,maxSpread());if(!fileName)$('sourceTag').textContent='ספר לדוגמה · '+count()+' עמודים';if(!cloudCalc){metric('thickness','…');metric('sheets','…');metric('weight','…');metric('wrap','…');$('status').textContent='הנתונים נשלחים לחישוב בענן…';$('checkSummary').textContent='חישוב ענן';$('statusIcon').className='warning'}
 render();cinema?.update();requestCalc();
}
function addGuides(el){if(view!=='proof'||!$('guides').checked)return;const b=$('sourceSize').value==='bleed'?n('bleed'):0,w=n('width')+2*b,h=n('height')+2*b;for(const [cls,x,y]of [['trim',b,b],['safe',b+n('safe'),b+n('safe')]]){const d=document.createElement('div');d.className='guide '+cls;d.style.inset=`${y/h*100}% ${x/w*100}%`;el.append(d)}const d=document.createElement('div');d.className='guide gutter';d.style.top=b/h*100+'%';d.style.bottom=b/h*100+'%';d.style.width=n('gutter')/w*100+'%';d.style[el.id==='leftPage'?'right':'left']=b/w*100+'%';el.append(d)}
function demoPage(el,index){const d=document.createElement('div');d.className='demo-page'+(index===1?' title-page':'');if(index===1){const h=document.createElement('h3');h.textContent=$('title').value;const p=document.createElement('p');p.textContent=$('author').value;d.append(h,p)}else{const small=document.createElement('div');small.className='chapter-label';small.textContent='תצוגת הדגמה';const h=document.createElement('h3');h.textContent='לפני שהסיפור מתחיל';d.append(small,h);for(const text of ['בקרוב, בין הדפים האלה, יתחיל הסיפור שלך.','טען כתב יד כדי לקבל עמודים מעובדים מהשרת.','הדפדפן מציג רק את הפלט שחזר מהענן.']){const p=document.createElement('p');p.textContent=text;d.append(p)}}el.append(d);const num=document.createElement('span');num.className='page-num';num.textContent=index;el.append(num)}
async function previewUrl(meta,index=1,width=1200){const key=[meta.id,index,width].join(':');if(previewCache.has(key))return previewCache.get(key);const res=await cloudFetch(`/api/page-preview?id=${encodeURIComponent(meta.id)}&page=${index}&width=${width}`);const blob=await res.blob();const url=URL.createObjectURL(blob);previewCache.set(key,url);return url}
async function imageFromMeta(meta,index=1,width=1600){const url=await previewUrl(meta,index,width);return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('הפלט מהשרת אינו תמונה תקינה'));img.src=url})}
async function fill(el,index,token){el.replaceChildren();el.setAttribute('aria-label',index>=1&&index<=count()?'עמוד '+index:'עמוד ריק');if(index<1||index>count()){addGuides(el);return}if(cloudFiles.manuscript){const url=await previewUrl(cloudFiles.manuscript,index,1400);if(token!==renderId)return;const img=document.createElement('img');img.alt='עמוד '+index;img.src=url;Object.assign(img.style,{position:'absolute',maxWidth:'100%',maxHeight:'100%',width:'auto',height:'auto',left:'50%',top:'50%',transform:'translate(-50%,-50%)',objectFit:'contain'});el.append(img)}else demoPage(el,index);addGuides(el)}
async function render(){if(view==='shelf')return;const token=++renderId,first=page*2,stage=$('stage'),spread=$('spread');const extra=$('sourceSize').value==='bleed'?2*n('bleed'):0,ratio=2*(n('width')+extra)/(n('height')+extra);const pad=stage.clientWidth<600?28:80,availableW=stage.clientWidth-pad,availableH=stage.clientHeight-116;const baseW=Math.min(availableW,availableH*ratio),zoom=n('zoom')/100,w=baseW*zoom;spread.style.width=w+'px';spread.style.height=w/ratio+'px';stage.classList.toggle('zoomed',zoom>1.01);const sheets=Number(cloudCalc?.sheets||1),depth=Math.min(18,sheets*Number(cloudCalc?.caliperMm||.1)*(w/2)/n('width'));const leftDepth=Math.max(1,depth*(1-first/count())),rightDepth=Math.max(1,depth*first/count());$('leftPage').style.boxShadow=`0 1px 0 #d0c7b3,0 ${leftDepth/2}px 0 #ede6d6,0 ${leftDepth}px 0 #afa793`;$('rightPage').style.boxShadow=`0 1px 0 #d0c7b3,0 ${rightDepth/2}px 0 #ede6d6,0 ${rightDepth}px 0 #afa793`;$('pageLabel').textContent=first===0?'עמוד 1':first>=count()?'עמוד '+count():`עמודים ${first}–${Math.min(first+1,count())}`;$('prev').disabled=page===0||turning;$('next').disabled=page>=maxSpread()||turning;$('pageSlider').value=page;$('jump').value=Math.max(1,Math.min(first||1,count()));try{await Promise.all([fill($('leftPage'),first+1,token),fill($('rightPage'),first,token)])}catch(e){if(token===renderId)toast('לא ניתן לקבל את העמוד מהשרת: '+e.message)}}
function setView(v){view=v;scheduleLocalSave();$('stage').classList.remove('shelf','open','proof');$('stage').classList.add(v);if(v==='shelf'){$('stage').classList.remove('zoomed');++renderId}document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-selected',String(b.dataset.view===v))});$('shelfControls').hidden=v!=='shelf';$('readerControls').hidden=v==='shelf';$('timeline').hidden=v==='shelf';$('sceneName').textContent=v==='shelf'?'תצוגת כריכה':v==='proof'?'חיתוך · גלישה · שוליים':'קריאה מימין לשמאל';$('stageHint').replaceChildren(document.createTextNode(v==='shelf'?'לחץ על הספר לפתיחה':v==='proof'?'קווים מקווקווים מסמנים את אזורי ההדפסה':'העמודים מתקבלים מהשרת לפי הצורך'));if(v==='proof')$('inspection').open=true;update()}
async function openBook(){if(busy||turning)return;turning=true;if(!reducedMotion.matches){const animation=$('book').animate([{transform:`rotateY(${n('rotation')}deg) rotateX(2deg)`},{transform:'translateZ(180px) rotateY(0deg) translateY(-10px)',opacity:1},{transform:'translateZ(260px) rotateY(8deg)',opacity:0}],{duration:600,easing:'cubic-bezier(.25,.75,.25,1)',fill:'forwards'});await animation.finished;animation.cancel()}setView('open');if(!reducedMotion.matches)$('spread').animate([{opacity:0,transform:'translateY(18px) scale(.92)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:400,easing:'ease-out'});turning=false;render()}
async function navigate(target,animate=true){if(turning||busy)return;target=Math.max(0,Math.min(maxSpread(),target));if(view==='shelf')setView('open');if(target===page)return;const forwards=target>page;turning=true;if(animate&&!reducedMotion.matches&&Math.abs(target-page)===1&&view==='open'){const sheet=$('turnSheet');sheet.replaceChildren();sheet.className='turn-sheet'+(forwards?' backward':'');sheet.style.display='block';const source=$(forwards?'leftPage':'rightPage'),clone=source.cloneNode(true);clone.removeAttribute('id');Object.assign(clone.style,{position:'absolute',inset:'0',width:'100%',boxShadow:'none'});sheet.append(clone);const animation=sheet.animate([{transform:'rotateY(0deg)',opacity:1},{transform:`rotateY(${forwards?160:-160}deg)`,opacity:.15}],{duration:440,easing:'cubic-bezier(.3,.1,.3,1)',fill:'forwards'});page=target;await render();await animation.finished;animation.cancel();sheet.style.display='none';sheet.replaceChildren()}else{page=target;await render()}turning=false;$('prev').disabled=page===0;$('next').disabled=page>=maxSpread();scheduleLocalSave()}
function setLoading(value,text='שולח לענן…'){busy=value;$('loading').hidden=!value;$('loadingText').textContent=text;$('file').disabled=value;cloudStatus(value?'מעלה לענן…':'מחובר לענן',value?'working':'ok')}
async function uploadCloud(file,kind){const form=new FormData();form.append('file',file,file.name);form.append('kind',kind);const res=await cloudFetch('/api/upload',{method:'POST',body:form});const data=await res.json();if(!data.emailSent)throw Error('השרת לא אישר שליחת עותק במייל');return data.file}
async function loadFile(file){if(!file||busy)return;requestPersistentLocalStorage();if(!/\.(pdf|docx)$/i.test(file.name)){toast('יש לבחור קובץ PDF או DOCX');return}setLoading(true,'שולח את '+file.name+' לענן…');try{const meta=await uploadCloud(file,'manuscript');await storeLocalUpload('manuscript',file,meta);cloudFiles.manuscript=meta;++renderId;++contentRevision;mode=meta.mode||(/\.pdf$/i.test(file.name)?'pdf':'docx');dimensions=meta.dimensions||null;fileName=meta.name||file.name;page=0;$('count').max=Math.max(10000,meta.pageCount||1);$('count').value=meta.pageCount||1;$('count').disabled=true;if(meta.dimensions?.[0]){$('width').value=Number(meta.dimensions[0][0]).toFixed(1);$('height').value=Number(meta.dimensions[0][1]).toFixed(1)}$('sourceSize').value='trim';$('sourceTag').textContent=fileName+' · '+count()+' עמודים';$('sourceBadge').textContent=mode==='pdf'?'PDF · ענן':'Word · ענן';$('zoom').value=100;$('zoomValue').textContent='100%';cloudCalc=null;await requestCalcNow();setView('open');scheduleLocalSave();toast('הקובץ נשמר בדפדפן + בענן · עותק נשלח במייל · העיבוד מתבצע בשרת')}catch(e){cloudStatus('העלאה נכשלה','error');toast('לא ניתן להעלות את הקובץ: '+e.message)}finally{setLoading(false);$('file').value=''}}
$('file').onchange=()=>loadFile($('file').files[0]);$('dropzone').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('dragover')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragover');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragover');loadFile(e.dataTransfer.files[0])};
$('book').onclick=openBook;$('openBook').onclick=openBook;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(!busy&&!turning)setView(b.dataset.view)});$('prev').onclick=()=>navigate(page-1);$('next').onclick=()=>navigate(page+1);$('go').onclick=()=>navigate(Math.floor(n('jump')/2),false);$('jump').onkeydown=e=>{if(e.key==='Enter')$('go').click()};$('pageSlider').oninput=()=>navigate(n('pageSlider'),false);$('rotation').oninput=()=>$('stage').style.setProperty('--rotation',n('rotation')+'deg');$('zoom').oninput=()=>{$('zoomValue').textContent=n('zoom')+'%';render()};$('fit').onclick=()=>{$('zoom').value=100;$('zoomValue').textContent='100%';render()};$('guides').onchange=render;
for(const id of ids){$(id).addEventListener('input',()=>{update();scheduleLocalSave()});$(id).addEventListener('change',()=>{if($(id).type==='number')$(id).value=n(id);update();scheduleLocalSave()})}
$('paper').addEventListener('change',()=>{const preset={cream:[.105,80],white:[.1,80],thin:[.085,70],coated:[.095,115]}[$('paper').value];if(preset){$('caliper').value=preset[0];$('gsm').value=preset[1]}update()});$('binding').addEventListener('change',()=>{$('board').value=$('binding').value==='hard'?2.5:.4;$('endpapers').value=$('binding').value==='hard'?4:0;update()});
async function coverBitmap(file,kind='front'){requestPersistentLocalStorage();cloudStatus('מעלה כריכה לענן…','working');const meta=await uploadCloud(file,kind);await storeLocalUpload(kind,file,meta);cloudFiles[kind]=meta;const img=await imageFromMeta(meta,1,2048);img.__cloudMeta=meta;scheduleLocalSave();cloudStatus('הכריכה עובדה בענן + נשמרה מקומית','ok');return img}
$('coverFile').onchange=async()=>{const f=$('coverFile').files[0];if(!f)return;try{const src=await coverBitmap(f,'front');coverUrl=src.src;const art=document.querySelector('.cover-art'),preview=$('frontCoverPreview');art.style.backgroundImage=`url("${coverUrl}")`;art.style.backgroundSize='contain';art.style.backgroundRepeat='no-repeat';document.querySelector('.cover-type').hidden=true;if(preview){preview.style.backgroundImage=`url("${coverUrl}")`;preview.classList.add('has-cover')}cinema?.setFront(src);toast('החזית עובדה בשרת · עותק הקובץ נשלח במייל')}catch(e){toast('לא ניתן לעבד את קובץ הכריכה: '+e.message)}finally{$('coverFile').value=''}};
$('resetCover').onclick=()=>{coverUrl=null;cloudFiles.front=null;removeLocalUpload('front');document.querySelector('.cover-art').style.backgroundImage='';document.querySelector('.cover-art').style.backgroundSize='';document.querySelector('.cover-type').hidden=false;const preview=$('frontCoverPreview');if(preview){preview.style.backgroundImage='';preview.classList.remove('has-cover')}$('coverFile').value='';cinema?.setFront(null);scheduleLocalSave()};
$('togglePanel').onclick=()=>{$('app').classList.toggle('panel-hidden');update()};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('workspace').requestFullscreen()}catch{toast('מסך מלא אינו זמין בדפדפן הזה')}};
$('export').onclick=()=>{const names={title:'שם הספר',author:'מחבר',width:'רוחב חיתוך במ״מ',height:'גובה חיתוך במ״מ',count:'עמודים',caliper:'עובי דף במ״מ',gsm:'משקל נייר בגרם למ״ר',board:'עובי צד כריכה במ״מ',endpapers:'דפי בטנה נוספים',bleed:'גלישה במ״מ',safe:'מרחק בטוח במ״מ',gutter:'אובדן בשדרה במ״מ'};const lines=['מפרט הדפסה — '+$('title').value,'',...Object.entries(names).map(([id,label])=>label+': '+$(id).value),...['paper','binding','finish','sourceSize'].map(id=>$(id).selectedOptions[0].textContent),'','עובי ספר משוער: '+$('thickness').textContent,'דפים פיזיים: '+$('sheets').textContent,'משקל גוף הספר: '+$('weight').textContent,'פריסת כריכה רכה כולל גלישה: '+$('wrap').textContent,'','קובץ: '+(fileName||'הדגמה'),$('status').textContent,'','החישובים לעיל התקבלו משרת הענן. אומדן בלבד; יש לאשר מול בית הדפוס.'];const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));a.href=url;a.download='book-print-spec.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.addEventListener('input',e=>{if(e.target?.matches?.('input,select,textarea'))scheduleLocalSave()},true);document.addEventListener('change',e=>{if(e.target?.matches?.('input,select,textarea'))scheduleLocalSave()},true);
document.addEventListener('fullscreenchange',()=>setTimeout(update,100));window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(update,100)});document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();navigate(page+1)}if(e.key==='ArrowRight'){e.preventDefault();navigate(page-1)}if(e.key==='Escape'&&!document.fullscreenElement)setView('shelf')});let touchStart=null;$('stage').addEventListener('touchstart',e=>{touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});$('stage').addEventListener('touchend',e=>{if(!touchStart||view==='shelf'||n('zoom')>100)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*2)navigate(page+(dx>0?1:-1));touchStart=null},{passive:true});
function getBookSpec(){return {title:$('title').value||'הספר שלי',author:$('author').value||'שם המחבר',width:n('width'),height:n('height'),count:count(),thickness:Number(cloudCalc?.thicknessMm||1),block:Number(cloudCalc?.blockMm||1),paper:({cream:'#f3eedf',white:'#ffffff',thin:'#f6f5ed',coated:'#fbfcfd',custom:'#f2eee4'})[$('paper').value],gloss:$('finish').value==='gloss',mode,revision:contentRevision}}
async function pageBitmap(index,width=1100){const spec=getBookSpec(),result=document.createElement('canvas');result.width=width;result.height=Math.round(width*spec.height/spec.width);const ctx=result.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,result.width,result.height);if(index<1||index>count())return result;if(cloudFiles.manuscript){const img=await imageFromMeta(cloudFiles.manuscript,index,width);result.width=img.naturalWidth||img.width;result.height=img.naturalHeight||img.height;result.getContext('2d').drawImage(img,0,0,result.width,result.height);return result}ctx.fillStyle='#283b48';ctx.textAlign='center';ctx.direction='rtl';ctx.font=`700 ${width*.08}px Frank,serif`;ctx.fillText(spec.title,width/2,result.height*.42);ctx.font=`${width*.04}px Heebo,Arial`;ctx.fillText(spec.author,width/2,result.height*.55);return result}
function cloudState(){return {source:{manuscript:cloudFiles.manuscript,front:cloudFiles.front,wrap:cloudFiles.wrap},settings:settings(),spec:getBookSpec()}}
async function renderMovie(movie){cloudStatus('הסרטון נשלח לרינדור בענן…','working');const res=await cloudFetch('/api/movie/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...cloudState(),movie})});const data=await res.json();cloudStatus('הרינדור הושלם בענן','ok');return data}
async function renderWrap(wrap){if(!cloudFiles.wrap)throw Error('לא נטענה כריכה רציפה');cloudStatus('מחשב פריסת כריכה בענן…','working');const res=await cloudFetch('/api/wrap/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileId:cloudFiles.wrap.id,spec:getBookSpec(),wrap})});const data=await res.json();cloudStatus('פריסת הכריכה הוחזרה מהענן','ok');return data}
cinema=initCinema({getSpec:getBookSpec,pageBitmap,coverBitmap,toast,renderMovie,renderWrap,isCloudHeadless:()=>headlessRender,cloudState,onProjectChange:scheduleLocalSave,removeLocalKind:removeLocalUpload});
async function bootCloudRender(){if(!headlessRender)return;try{document.documentElement.classList.add('cloud-render');const id=params.get('__cloudRenderJob');const res=await cloudFetch('/api/render-job/'+encodeURIComponent(id),{},true);const job=await res.json();for(const [id,value] of Object.entries(job.settings||{}))if($(id))$(id).value=value;Object.assign(cloudFiles,job.source||{});if(cloudFiles.manuscript){mode=cloudFiles.manuscript.mode||'pdf';dimensions=cloudFiles.manuscript.dimensions||null;fileName=cloudFiles.manuscript.name||'';$('count').value=cloudFiles.manuscript.pageCount||job.spec?.count||1}contentRevision++;await requestCalcNow();if(cloudFiles.front)cinema.setFront(await imageFromMeta(cloudFiles.front,1,2048));if(cloudFiles.wrap){const img=await imageFromMeta(cloudFiles.wrap,1,2600);cinema.setWrapFromCloud?.(img,cloudFiles.wrap.name,job.movie?.wrap)}await cinema.serverRender?.(job.movie||{});}catch(e){window.__BOOK_RENDER_ERROR__=e.message;window.__BOOK_RENDER_DONE__=true;console.error(e)}}
async function boot(){update();if(headlessRender){await bootCloudRender();return}await restoreLocalProject()}boot();
