import puppeteer from '@cloudflare/puppeteer';

const JSON_HEADERS = {'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'authorization, content-type','access-control-allow-methods':'GET,POST,OPTIONS'};
const enc = new TextEncoder();
const safeJson = (data,status=200,extra={}) => new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
const errorJson = (message,status=400) => safeJson({ok:false,error:String(message)},status);
const rid = () => crypto.randomUUID();
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const htmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function tokenFrom(request){const a=request.headers.get('authorization')||'';return a.toLowerCase().startsWith('bearer ')?a.slice(7).trim():''}
function authorized(request,env){const token=tokenFrom(request);return Boolean(token && ((env.BOOK_API_TOKEN&&token===env.BOOK_API_TOKEN)||(env.RENDER_TOKEN&&token===env.RENDER_TOKEN)))}
function renderAuthorized(request,env){return Boolean(env.RENDER_TOKEN&&tokenFrom(request)===env.RENDER_TOKEN)}
function maxUpload(env){return clamp(num(env.MAX_UPLOAD_BYTES,28*1024*1024),1024,35*1024*1024)}
function inferMime(name,mime=''){if(mime)return mime;const ext=name.toLowerCase().split('.').pop();return ({pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',bmp:'image/bmp',svg:'image/svg+xml'})[ext]||'application/octet-stream'}
function safeName(name){return String(name||'upload.bin').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,180)||'upload.bin'}
async function kvGetJson(env,key){const v=await env.BOOK_JOBS.get(key);return v?JSON.parse(v):null}
async function kvPutJson(env,key,value,opts={}){await env.BOOK_JOBS.put(key,JSON.stringify(value),opts)}
async function fileMeta(env,id){return await kvGetJson(env,'file:'+id)}
function internalFileUrl(origin,id,env){return `${origin}/api/internal-file/${encodeURIComponent(id)}?token=${encodeURIComponent(env.RENDER_TOKEN||'')}`}

function calculate(body={}){
 const s=body.settings||{};const count=Math.max(1,Math.floor(num(s.count,1))),endpapers=Math.max(0,Math.floor(num(s.endpapers))),caliper=Math.max(0,num(s.caliper,.1)),board=Math.max(0,num(s.board,.4)),width=Math.max(.1,num(s.width,145)),height=Math.max(.1,num(s.height,210)),gsm=Math.max(1,num(s.gsm,80)),bleed=Math.max(0,num(s.bleed,3));
 const sheets=Math.ceil(count/2)+endpapers,blockMm=sheets*caliper,thicknessMm=blockMm+2*board,weightGrams=Math.round(sheets*width*height/1e6*gsm),wrapWidthMm=2*width+blockMm+2*bleed,wrapHeightMm=height+2*bleed;
 const mode=body.mode||body.source?.mode||'demo',dimensions=Array.isArray(body.dimensions)?body.dimensions:(Array.isArray(body.source?.dimensions)?body.source.dimensions:null);let warning=mode!=='pdf',summary=mode==='demo'?'ממתין לטעינת כתב יד':mode==='docx'?'Word · עיבוד שרת':'PDF · עיבוד שרת';let message=mode==='demo'?'עמודי הדגמה בלבד. טען כתב יד כדי שהשרת יפיק תצוגה.':mode==='docx'?'המסמך עובד בשרת. עימוד Word עשוי להיות שונה מ־PDF סופי.':'ה־PDF עובד בשרת ומוחזר כתמונות תצוגה.';
 if(dimensions?.length){const extra=s.sourceSize==='bleed'?2*bleed:0;const mismatch=dimensions.filter(d=>Array.isArray(d)&&(Math.abs(num(d[0])-width-extra)>1||Math.abs(num(d[1])-height-extra)>1)).length;message+=` מידות המקור: ${num(dimensions[0][0]).toFixed(1)} × ${num(dimensions[0][1]).toFixed(1)} מ״מ.`;if(mismatch){warning=true;summary=`${mismatch} עמודים עם מידות שונות מהמפרט`;message+=` ${mismatch} עמודים אינם תואמים למידות המפרט.`}else message+=' מידות העמודים תואמות למפרט.'}
 if(count%2)message+=' בסוף הספר נוסף צד ריק להשלמת דף.';if(s.sourceSize==='trim'&&bleed>0)message+=' הקובץ מוגדר במידת חיתוך; גלישה חסרה אינה נוצרת אוטומטית.';
 return {sheets,caliperMm:caliper,blockMm,thicknessMm,weightGrams,wrapWidthMm,wrapHeightMm,validation:{warning,summary,message}};
}

async function withBrowser(env,fn){const browser=await puppeteer.launch(env.BROWSER);try{return await fn(browser)}finally{await browser.close().catch(()=>{})}}
async function setupPdfPage(page){await page.setViewport({width:1400,height:1800,deviceScaleFactor:1});await page.goto('about:blank');await page.addScriptTag({url:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js'});await page.evaluate(()=>{if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'})}
async function inspectPdf(env,origin,meta){return withBrowser(env,async browser=>{const page=await browser.newPage();await setupPdfPage(page);return await page.evaluate(async url=>{const ab=await (await fetch(url)).arrayBuffer();const doc=await pdfjsLib.getDocument({data:ab}).promise;const dims=[];for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),v=p.getViewport({scale:1});dims.push([v.width*25.4/72,v.height*25.4/72])}return {pageCount:doc.numPages,dimensions:dims,mode:'pdf'}},internalFileUrl(origin,meta.id,env))})}
async function inspectDocx(env,origin,meta){return withBrowser(env,async browser=>{const page=await browser.newPage();await page.setViewport({width:1300,height:1800,deviceScaleFactor:1});await page.goto('about:blank');await page.addScriptTag({url:'https://cdn.jsdelivr.net/npm/docx-preview@0.3.7/dist/docx-preview.min.js'});return await page.evaluate(async url=>{document.body.innerHTML='<div id="host"></div>';const ab=await (await fetch(url)).arrayBuffer();await docx.renderAsync(ab,document.getElementById('host'),null,{breakPages:true,ignoreLastRenderedPageBreak:false,useBase64URL:true});if(document.fonts?.ready)await document.fonts.ready;const pages=[...document.querySelectorAll('section.docx')];if(!pages.length)throw Error('לא נמצאו עמודים במסמך Word');const dimensions=pages.map(el=>{const r=el.getBoundingClientRect();return [r.width*25.4/96,r.height*25.4/96]});return {pageCount:pages.length,dimensions,mode:'docx'}},internalFileUrl(origin,meta.id,env))})}
async function inspectUpload(env,origin,meta){if(meta.kind==='manuscript'){if(meta.mime==='application/pdf'||/\.pdf$/i.test(meta.name))return inspectPdf(env,origin,meta);return inspectDocx(env,origin,meta)}if(meta.mime==='application/pdf'||/\.pdf$/i.test(meta.name)){const info=await inspectPdf(env,origin,meta);return {...info,pageCount:info.pageCount||1}}return {pageCount:1,dimensions:null,mode:'image'}}

async function renderPdfPreview(env,origin,meta,pageNo,width){return withBrowser(env,async browser=>{const page=await browser.newPage();await setupPdfPage(page);await page.evaluate(async({url,pageNo,width})=>{document.body.style.margin='0';const ab=await (await fetch(url)).arrayBuffer(),doc=await pdfjsLib.getDocument({data:ab}).promise,p=await doc.getPage(Math.max(1,Math.min(pageNo,doc.numPages))),raw=p.getViewport({scale:1}),vp=p.getViewport({scale:width/raw.width});const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);document.body.append(c);await p.render({canvasContext:c.getContext('2d'),viewport:vp,background:'#fff'}).promise},{url:internalFileUrl(origin,meta.id,env),pageNo,width});const el=await page.$('canvas');return new Uint8Array(await el.screenshot({type:'png'}))})}
async function renderDocxPreview(env,origin,meta,pageNo,width){return withBrowser(env,async browser=>{const page=await browser.newPage();await page.setViewport({width:Math.max(900,width+120),height:1800,deviceScaleFactor:1});await page.goto('about:blank');await page.addScriptTag({url:'https://cdn.jsdelivr.net/npm/docx-preview@0.3.7/dist/docx-preview.min.js'});const selector=await page.evaluate(async({url,pageNo,width})=>{document.body.style.margin='0';document.body.innerHTML='<div id="host"></div>';const ab=await (await fetch(url)).arrayBuffer();await docx.renderAsync(ab,document.getElementById('host'),null,{breakPages:true,ignoreLastRenderedPageBreak:false,useBase64URL:true});if(document.fonts?.ready)await document.fonts.ready;const pages=[...document.querySelectorAll('section.docx')];const i=Math.max(0,Math.min(pageNo-1,pages.length-1));pages.forEach((p,j)=>{p.style.display=j===i?'block':'none';p.style.margin='0';p.style.boxShadow='none'});const target=pages[i],r=target.getBoundingClientRect(),scale=width/r.width;target.style.transformOrigin='top left';target.style.transform=`scale(${scale})`;document.body.style.width=Math.ceil(r.width*scale)+'px';document.body.style.height=Math.ceil(r.height*scale)+'px';target.id='capture';return '#capture'},{url:internalFileUrl(origin,meta.id,env),pageNo,width});const el=await page.$(selector);return new Uint8Array(await el.screenshot({type:'png'}))})}
async function preview(env,origin,meta,pageNo,width){if(meta.mode==='image'||meta.mime?.startsWith('image/')){const obj=await env.BOOK_FILES.get(meta.key);if(!obj)throw Error('הקובץ לא נמצא');return {body:obj.body,type:meta.mime||'image/png',cache:false}}const key=`previews/${meta.id}/${pageNo}-${width}.png`;const cached=await env.BOOK_FILES.get(key);if(cached)return {body:cached.body,type:'image/png',cache:true};const bytes=meta.mode==='docx'?await renderDocxPreview(env,origin,meta,pageNo,width):await renderPdfPreview(env,origin,meta,pageNo,width);await env.BOOK_FILES.put(key,bytes,{httpMetadata:{contentType:'image/png'}});return {body:bytes,type:'image/png',cache:false}}

async function sendResendCopy(env,origin,meta){if(!env.RESEND_API_KEY)throw Error('RESEND_API_KEY לא הוגדר');if(!env.EMAIL_TO)throw Error('EMAIL_TO לא הוגדר');if(!env.RESEND_FROM)throw Error('RESEND_FROM לא הוגדר');const token=rid();await kvPutJson(env,'mail:'+token,{key:meta.key,name:meta.name,mime:meta.mime},{expirationTtl:3600});const path=`${origin}/api/mail-file?token=${encodeURIComponent(token)}`;const payload={from:env.RESEND_FROM,to:[env.EMAIL_TO],subject:`Book Studio upload — ${meta.name}`,html:`<div dir="rtl"><h2>הועלה קובץ לסטודיו הספר</h2><p><b>שם:</b> ${htmlEscape(meta.name)}</p><p><b>סוג:</b> ${htmlEscape(meta.kind)}</p><p><b>גודל:</b> ${(meta.size/1024/1024).toFixed(2)} MB</p><p>הקובץ מצורף להודעה זו באופן אוטומטי.</p></div>`,attachments:[{path,filename:meta.name}]};const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+env.RESEND_API_KEY,'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||data.error||`Resend HTTP ${r.status}`);return data.id||true}

async function handleUpload(request,env,url){if(!authorized(request,env))return errorJson('נדרש קוד גישה לשרת',401);let form;try{form=await request.formData()}catch{return errorJson('טופס ההעלאה אינו תקין')};const file=form.get('file'),kind=String(form.get('kind')||'');if(!(file instanceof File))return errorJson('לא התקבל קובץ');if(!['manuscript','front','wrap'].includes(kind))return errorJson('סוג העלאה לא מוכר');if(file.size<=0)return errorJson('הקובץ ריק');if(file.size>maxUpload(env))return errorJson(`כדי להבטיח שליחה כקובץ מצורף דרך Resend, גודל העלאה מרבי הוא ${(maxUpload(env)/1024/1024).toFixed(0)}MB`,413);const name=safeName(file.name),mime=inferMime(name,file.type);if(kind==='manuscript'&&!(/\.pdf$/i.test(name)||/\.docx$/i.test(name)))return errorJson('כתב יד חייב להיות PDF או DOCX');if(kind!=='manuscript'&&!(mime.startsWith('image/')||/\.pdf$/i.test(name)))return errorJson('כריכה חייבת להיות תמונה או PDF');const id=rid(),day=new Date().toISOString().slice(0,10),key=`uploads/${day}/${id}/${name}`;let meta={id,key,name,kind,mime,size:file.size,createdAt:new Date().toISOString(),mode:kind==='manuscript'?(/\.pdf$/i.test(name)?'pdf':'docx'):(mime.startsWith('image/')?'image':'pdf')};try{await env.BOOK_FILES.put(key,file.stream(),{httpMetadata:{contentType:mime,contentDisposition:`inline; filename="${name.replace(/"/g,'')}"`},customMetadata:{id,kind,name}});await kvPutJson(env,'file:'+id,meta,{expirationTtl:60*60*24*30});const inspection=await inspectUpload(env,url.origin,meta);meta={...meta,...inspection};await kvPutJson(env,'file:'+id,meta,{expirationTtl:60*60*24*30});const resendId=await sendResendCopy(env,url.origin,meta);return safeJson({ok:true,emailSent:true,resendId,file:meta})}catch(e){await env.BOOK_FILES.delete(key).catch(()=>{});await env.BOOK_JOBS.delete('file:'+id).catch(()=>{});return errorJson(e.message||e,500)}}

async function handlePagePreview(request,env,url){if(!authorized(request,env))return errorJson('נדרש קוד גישה לשרת',401);const id=url.searchParams.get('id'),pageNo=Math.max(1,Math.floor(num(url.searchParams.get('page'),1))),width=clamp(Math.floor(num(url.searchParams.get('width'),1200)),300,2600),meta=await fileMeta(env,id);if(!meta)return errorJson('קובץ לא נמצא',404);try{const out=await preview(env,url.origin,meta,pageNo,width);return new Response(out.body,{headers:{'content-type':out.type,'cache-control':'private, max-age=3600','access-control-allow-origin':'*'}})}catch(e){return errorJson(e.message||e,500)}}

async function hashText(text){const d=await crypto.subtle.digest('SHA-256',enc.encode(text));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,24)}
async function signedImageUrl(env,origin,key,mime='image/png'){const token=rid();await kvPutJson(env,'image:'+token,{key,mime},{expirationTtl:3600});return `${origin}/api/generated-image?token=${encodeURIComponent(token)}`}
async function loadWrapSource(env,origin,meta){if(meta.mode==='image'||meta.mime?.startsWith('image/'))return internalFileUrl(origin,meta.id,env);const width=2600,key=`previews/${meta.id}/1-${width}.png`;if(!(await env.BOOK_FILES.head(key)))await preview(env,origin,meta,1,width);return `${origin}/api/internal-object?token=${encodeURIComponent(env.RENDER_TOKEN||'')}&key=${encodeURIComponent(key)}`}
async function handleWrapRender(request,env,url){if(!authorized(request,env))return errorJson('נדרש קוד גישה לשרת',401);let body;try{body=await request.json()}catch{return errorJson('JSON לא תקין')};const meta=await fileMeta(env,body.fileId);if(!meta)return errorJson('קובץ הכריכה לא נמצא',404);const spec=body.spec||{},wrap=body.wrap||{},bleed=clamp(num(wrap.bleed,0),0,15),spine=clamp(num(wrap.spine,0),0,150)||num(spec.block,1),total=num(spec.width,145)*2+spine+bleed*2,height=num(spec.height,210)+bleed*2;const signature=await hashText(JSON.stringify({id:meta.id,spec:{width:spec.width,height:spec.height,block:spec.block},wrap})),base=`generated-wrap/${meta.id}/${signature}`,keys={atlas:`${base}/atlas.png`,front:`${base}/front.png`,back:`${base}/back.png`,spine:`${base}/spine.png`};let ready=true;for(const key of Object.values(keys))if(!(await env.BOOK_FILES.head(key))){ready=false;break}
 if(!ready){const sourceUrl=await loadWrapSource(env,url.origin,meta);await withBrowser(env,async browser=>{const page=await browser.newPage();await page.setViewport({width:1600,height:1800,deviceScaleFactor:1});await page.goto('about:blank');await page.evaluate(async({sourceUrl,spec,wrap,bleed,spine,total,height})=>{document.body.style.margin='0';const img=new Image();img.crossOrigin='anonymous';await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('לא ניתן לטעון כריכה'));img.src=sourceUrl});const W=2048,scale=W/total,H=Math.max(64,Math.round(height*scale));const atlas=document.createElement('canvas');atlas.id='atlas';atlas.width=W;atlas.height=H;const x=atlas.getContext('2d');x.fillStyle=wrap.background||'#f0eadf';x.fillRect(0,0,W,H);const fit=(wrap.fit==='contain'?Math.min(W/img.naturalWidth,H/img.naturalHeight):Math.max(W/img.naturalWidth,H/img.naturalHeight))*(num=>Number.isFinite(Number(num))?Number(num):100)(wrap.scale)/100;x.save();x.translate(W/2+(Number(wrap.x)||0)/100*W/2,H/2+(Number(wrap.y)||0)/100*H/2);x.rotate((Number(wrap.angle)||0)*Math.PI/180);x.drawImage(img,-img.naturalWidth*fit/2,-img.naturalHeight*fit/2,img.naturalWidth*fit,img.naturalHeight*fit);x.restore();document.body.append(atlas);const crop=(id,mmX,mmW)=>{const c=document.createElement('canvas');c.id=id;c.width=Math.max(32,Math.round(mmW*scale));c.height=Math.max(32,Math.round(Number(spec.height||210)*scale));c.getContext('2d').drawImage(atlas,mmX*scale,bleed*scale,mmW*scale,Number(spec.height||210)*scale,0,0,c.width,c.height);document.body.append(c)};const leftX=bleed,rightX=bleed+Number(spec.width||145)+spine;crop('left',leftX,Number(spec.width||145));crop('right',rightX,Number(spec.width||145));crop('spine',bleed+Number(spec.width||145),spine);const hebrew=wrap.order!=='reverse';document.getElementById(hebrew?'left':'right').id='front';document.getElementById(hebrew?'right':'left').id='back'},{sourceUrl,spec,wrap,bleed,spine,total,height});for(const [name,key] of Object.entries(keys)){const el=await page.$('#'+name),bytes=new Uint8Array(await el.screenshot({type:'png'}));await env.BOOK_FILES.put(key,bytes,{httpMetadata:{contentType:'image/png'}})}})}
 const urls={};for(const [name,key] of Object.entries(keys))urls[name]=await signedImageUrl(env,url.origin,key);return safeJson({ok:true,urls,total,height,spine})}

async function handleMovieRender(request,env,url){if(!authorized(request,env))return errorJson('נדרש קוד גישה לשרת',401);if(!env.RENDER_TOKEN)return errorJson('RENDER_TOKEN לא הוגדר בשרת',500);let job;try{job=await request.json()}catch{return errorJson('JSON לא תקין')};const id=rid();job.id=id;job.createdAt=new Date().toISOString();if(job.movie&&!job.movie.exporting)job.movie.quality=Math.min(720,num(job.movie.quality,720));await kvPutJson(env,'job:'+id,{...job,status:'rendering'},{expirationTtl:1800});let browser;try{browser=await puppeteer.launch(env.BROWSER);const page=await browser.newPage();await page.setViewport({width:1600,height:1000,deviceScaleFactor:1});const target=`${url.origin}/?__cloudRenderJob=${encodeURIComponent(id)}&__renderToken=${encodeURIComponent(env.RENDER_TOKEN)}`;await page.goto(target,{waitUntil:'networkidle2',timeout:60000});await page.waitForFunction('window.__BOOK_RENDER_DONE__ === true',{timeout:240000});const err=await page.evaluate(()=>window.__BOOK_RENDER_ERROR__||'');if(err)throw Error(err);const stored=await kvGetJson(env,'job:'+id);if(!stored?.resultKey)throw Error('הרינדור הסתיים בלי קובץ תוצאה');const dl=rid();await kvPutJson(env,'movie:'+dl,{key:stored.resultKey,mime:stored.resultMime||'video/webm',name:'book-promo.webm',size:stored.resultSize||0},{expirationTtl:3600});return safeJson({ok:true,jobId:id,url:`${url.origin}/api/movie-file?token=${encodeURIComponent(dl)}`,mime:stored.resultMime||'video/webm',size:stored.resultSize||0})}catch(e){const stored=await kvGetJson(env,'job:'+id)||job;await kvPutJson(env,'job:'+id,{...stored,status:'error',error:String(e.message||e)},{expirationTtl:1800});return errorJson('רינדור הסרטון בשרת נכשל: '+(e.message||e),500)}finally{if(browser)await browser.close().catch(()=>{})}}

async function handleMovieResult(request,env,url){if(!renderAuthorized(request,env))return errorJson('גישה פנימית בלבד',401);const id=url.searchParams.get('jobId');if(!id)return errorJson('חסר jobId');const job=await kvGetJson(env,'job:'+id);if(!job)return errorJson('עבודת רינדור לא נמצאה',404);const mime=request.headers.get('content-type')||'video/webm',key=`movies/${new Date().toISOString().slice(0,10)}/${id}.webm`;await env.BOOK_FILES.put(key,request.body,{httpMetadata:{contentType:mime}});const head=await env.BOOK_FILES.head(key);await kvPutJson(env,'job:'+id,{...job,status:'done',resultKey:key,resultMime:mime,resultSize:head?.size||0},{expirationTtl:1800});return safeJson({ok:true})}

async function streamMovie(request,env,url){const token=url.searchParams.get('token'),m=await kvGetJson(env,'movie:'+token);if(!m)return errorJson('קישור הסרטון פג או אינו תקין',404);const range=request.headers.get('range');let obj,status=200,headers={'content-type':m.mime||'video/webm','accept-ranges':'bytes','cache-control':'private, max-age=3600','access-control-allow-origin':'*','content-disposition':`inline; filename="${m.name||'book-promo.webm'}"`};if(range&&m.size){const match=/bytes=(\d*)-(\d*)/.exec(range);if(match){let start=match[1]?Number(match[1]):0,end=match[2]?Number(match[2]):m.size-1;start=clamp(start,0,m.size-1);end=clamp(end,start,m.size-1);obj=await env.BOOK_FILES.get(m.key,{range:{offset:start,length:end-start+1}});status=206;headers['content-range']=`bytes ${start}-${end}/${m.size}`;headers['content-length']=String(end-start+1)}}if(!obj)obj=await env.BOOK_FILES.get(m.key);if(!obj)return errorJson('קובץ הסרטון אינו קיים',404);if(status===200&&obj.size)headers['content-length']=String(obj.size);return new Response(obj.body,{status,headers})}

async function route(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:JSON_HEADERS});if(url.pathname==='/api/health')return safeJson({ok:true,service:'book-studio-cloud',time:new Date().toISOString()});if(url.pathname==='/api/calc'&&request.method==='POST'){try{return safeJson({ok:true,calc:calculate(await request.json())})}catch(e){return errorJson(e.message||e)}}if(url.pathname==='/api/upload'&&request.method==='POST')return handleUpload(request,env,url);if(url.pathname==='/api/page-preview'&&request.method==='GET')return handlePagePreview(request,env,url);if(url.pathname==='/api/wrap/render'&&request.method==='POST')return handleWrapRender(request,env,url);if(url.pathname==='/api/movie/render'&&request.method==='POST')return handleMovieRender(request,env,url);if(url.pathname==='/api/movie-result'&&request.method==='POST')return handleMovieResult(request,env,url);if(url.pathname==='/api/movie-file'&&request.method==='GET')return streamMovie(request,env,url);
 if(url.pathname.startsWith('/api/render-job/')&&request.method==='GET'){if(!renderAuthorized(request,env))return errorJson('גישה פנימית בלבד',401);const id=decodeURIComponent(url.pathname.slice('/api/render-job/'.length)),job=await kvGetJson(env,'job:'+id);return job?safeJson(job):errorJson('עבודת רינדור לא נמצאה',404)}
 if(url.pathname.startsWith('/api/internal-file/')&&request.method==='GET'){if(!env.RENDER_TOKEN||url.searchParams.get('token')!==env.RENDER_TOKEN)return errorJson('גישה פנימית בלבד',401);const id=decodeURIComponent(url.pathname.slice('/api/internal-file/'.length)),meta=await fileMeta(env,id);if(!meta)return errorJson('קובץ לא נמצא',404);const obj=await env.BOOK_FILES.get(meta.key);if(!obj)return errorJson('קובץ לא נמצא באחסון',404);return new Response(obj.body,{headers:{'content-type':meta.mime||'application/octet-stream','cache-control':'private, max-age=300','access-control-allow-origin':'*'}})}
 if(url.pathname==='/api/internal-object'&&request.method==='GET'){if(!env.RENDER_TOKEN||url.searchParams.get('token')!==env.RENDER_TOKEN)return errorJson('גישה פנימית בלבד',401);const key=url.searchParams.get('key')||'';if(!key.startsWith('previews/'))return errorJson('מפתח פנימי לא מורשה',403);const obj=await env.BOOK_FILES.get(key);if(!obj)return errorJson('אובייקט לא נמצא',404);return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'image/png','access-control-allow-origin':'*'}})}
 if(url.pathname==='/api/generated-image'&&request.method==='GET'){const token=url.searchParams.get('token'),m=await kvGetJson(env,'image:'+token);if(!m)return errorJson('קישור התמונה פג',404);const obj=await env.BOOK_FILES.get(m.key);if(!obj)return errorJson('תמונה לא נמצאה',404);return new Response(obj.body,{headers:{'content-type':m.mime||'image/png','cache-control':'private, max-age=3600','access-control-allow-origin':'*'}})}
 if(url.pathname==='/api/mail-file'&&request.method==='GET'){const token=url.searchParams.get('token'),m=await kvGetJson(env,'mail:'+token);if(!m)return errorJson('קישור הקובץ פג',404);const obj=await env.BOOK_FILES.get(m.key);if(!obj)return errorJson('קובץ לא נמצא',404);return new Response(obj.body,{headers:{'content-type':m.mime||'application/octet-stream','content-disposition':`attachment; filename="${safeName(m.name)}"`,'cache-control':'private, max-age=300'}})}
 return null;
}

export default {async fetch(request,env){try{const api=await route(request,env);if(api)return api;if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('Book Studio Cloud',{headers:{'content-type':'text/plain; charset=utf-8'}})}catch(e){console.error(e);return errorJson(e.message||'Internal error',500)}}};
